@startuml Programa

title Diagrama de Clases
header Proyecto
footer Diagrama 1

class Centro {
    - String nombre
    - ListaPacientes pacientes
    - ListaTerapeutas terapeutas

    + Centro(String nombre)
}

class Persona {
    - int rut
    - String nombre
    - int edad

    + Persona(String nombre, String rut, int edad)

    + int getRut()
    + void setRut(int rut)
    + String getNombre()
    + void setNombre(String nombre)
    + int getEdad()
    + void setEdad(int edad)

    + String obtenerDatos()
}

class ListaPacientes {
    - HashMap<String, Paciente> tablaHashPacientes

    + ListaPacientes()

    + boolean agregarPaciente(Paciente paciente)
    + String listarPacientes()
}

class Paciente {
    - String direccion
    - String historial
    - ListaSesiones sesiones
    
    + Paciente(String nombre, String rut, int edad, String direccion, String historialMedico)

    + String getUbicacion()
    + void setUbicacion(String ubicacion)
    + String getHistorial()
    + void setHistorial(String historial)

    + void agregarSesion(SesionTerapia sesion)
    + String listarSesiones()
    + String obtenerDatos()
}

class ListaTerapeutas {
    - HashMap<String, Terapeuta> tablaHashterapeutas

    + ListaTerapeutas()

    + boolean agregarTerapeuta(Terapeuta terapeuta)
    + String listarTerapeutas()
}

class Terapeuta {
    - String especialidad

    + Terapeuta(String nombre, String rut, int edad, String especialidad)
    
    + String getEspecialidad()
    + void setEspecialidad(String especialidad)

    + String obtenerDatos()
}

class ListaSesiones {
    - ArrayList<SesionTerapia> lista

    + ListaSesiones()

    + boolean agregarSesion(SesionTerapia sesion)
    + int largo()
    + String listarSesiones()
}

class SesionTerapia {
    - LocalDate fecha;
    - String tipoTerapia;
    - String duracion;
    - String observaciones;
    - int calificacionMejora;
    
    + SesionTerapia(LocalDate fecha, String tipoTerapia, String duracion, String observaciones, int calificacionMejora)

    + LocalDate getFecha()
    + void setFecha(LocalDate fecha)
    + String getTipoTerapia() 
    + void setTipoTerapia(String tipoTerapia)
    + String getDuracion()
    + void setDuracion(String duracion)
    + String getObservaciones() 
    + void setObservaciones(String observaciones)
    + int getCalificacionMejora()
    + void setCalificacionMejora(int calificacionMejora)

    + String obtenerDatos()
}

class Utilidades {
    # void limpiarPantalla()
    # String formatearRut(String rut)
    # void presioneTeclaParaContinuar()
    # void leerArchivoPacientes(Map<String, Paciente> tablaHashPacientes)
    # void guardarPacienteCSV(String nombre, String rut, int edad, String direccion, String historialMedico)
    # void leerArchivoSesiones(Map<String, Paciente> tablaHashPacientes)
    # void guardarSesionesCSV(LocalDate fecha, String tipoTerapia, String duracion, String observaciones, int calificacionMejora, String rut)
}

Centro -[#black]-* ListaPacientes : Contiene
Persona --|> Paciente : Es
Persona --|> Terapeuta : Es
ListaPacientes --|> Paciente : Contiene
ListaTerapeutas --|> Terapeuta : Contiene
Paciente --|> ListaSesiones : Contiene
Terapeuta --|> ListaSesiones : Contiene
ListaSesiones --|> SesionTerapia : Está hecha

@enduml
