@startuml Programa

title Diagrama MVC
header Proyecto
footer Diagrama 3


class Controlador {
    - Centro centro;

    - MenuPrincipal menu;
    - GestionarPaciente gestionP;
    - AgregarPaciente agregarP;
    - EliminarPaciente eliminarP;
    - ListarPacientes listarP;
    - SeguimientoPaciente seguirP;
    - ListarSesiones listarS;
    - GestionarSesion gestionS;
}

class Centro {
    - String nombre
    - ListaPacientes pacientes
    - ListaTerapeutas terapeutas

    + Centro(String nombre)
    
}

class ListaPacientes {
    - HashMap<String, Paciente> tablaHashPacientes

    + ListaPacientes()

    + boolean agregarPaciente(Paciente paciente)
    + String listarPacientes()
}

class ListaTerapeutas {
    - HashMap<String, Terapeuta> tablaHashterapeutas

    + ListaTerapeutas()

    + boolean agregarTerapeuta(Terapeuta terapeuta)
    + String listarTerapeutas()
}

interface MenuPrincipal {
    + JButton getGestionarPacientes()
    + JButton getSeguimientoPaciente()
    + JButton getGestionarSesiones()
    + JButton getSalirPrograma()
}

interface GestionarPaciente {
    + JButton getAgregarPaciente()
    + JButton getEliminarPaciente()
    + JButton getListarPacientes()
    + JButton getCerrarGestionarPacientes()
}

interface AgregarPaciente {
    + JTextField getNombreField()
    + JTextField getRutField()
    + JTextField getEdadField()
    + JTextField getDireccionField()
    + JTextField getHistorialField()
    + JButton getBotonAgregarPaciente()
    + JButton getCerrarAgregarPaciente()
}

interface EliminarPaciente {
    + JTextField getRutEliminarField()
    + JButton getBotonEliminarPaciente()
    + JButton getCerrarEliminarPaciente()
}

interface ListarPacientes {
    + JButton getCerrarListarPacientes()
}

interface SeguimientoPaciente {
    + JTextField getRutSeguirField()
    + JButton getBotonSeguirPaciente()
    + JButton getCerrarSeguimientoPaciente()
}

interface GestionarSesion {
    + JButton getAgregarSesion()
    + JButton getEliminarSesion()
    + JButton getFiltrarSesiones()
    + JButton getCerrarGestionarSesion()
}

interface AgregarSesion {
    + JTextField getRutTerapeutaField()
    + JTextField getRutPacienteField()
    + JTextField getFechaField()
    + JTextField getTerapiaField()
    + JTextField getNotaField()
    + JTextField getComentariosField()
    + JTextField getDuracionField()
    + JButton getBotonAgregarSesion()
    + JButton getCerrarAgregarSesion()
}

interface EliminarSesion {

}

interface FiltrarSesiones {

}

Centro --|> Controlador : Es llamado por
ListaPacientes --|> Centro : Contiene
ListaTerapeutas --|> Centro : Contiene

MenuPrincipal --|> Controlador : Es llamado por
GestionarPaciente --|> MenuPrincipal : Contiene
AgregarPaciente --|> GestionarPaciente : Es Manejado
EliminarPaciente --|> GestionarPaciente : Es Manejado
ListarPacientes --|> GestionarPaciente : Es Manejado
SeguimientoPaciente --|> MenuPrincipal : Contiene
GestionarSesion --|> MenuPrincipal : Contiene
AgregarSesion --|> GestionarSesion : Es Manejado
EliminarSesion --|> GestionarSesion : Es Manejado
FiltrarSesiones --|> GestionarSesion : Es Manejado

@enduml
