@startuml Programa

title Diagrama MVC
header Proyecto
footer Diagrama 3

class Controlador {
    private String rutAux; 
    private Centro centro;

    - MenuPrincipal menu;
    - GestionarPaciente gestionP;
    - AgregarPaciente agregarP;
    - EliminarPaciente eliminarP;
    - ListarPacientes listarP;
    - SeguimientoPaciente seguirP;
    - ListarSesiones listarS;
    - GestionarSesion gestionS;
    - AgregarSesion agregarS;
    - BuscarEliminarSesion buscarS;
    - EliminarSesion eliminarS;
    - FiltrarSesiones filtrarS;
    - ConsultaAño consultaA;
    - ConsultaTerapeuta consultaT;
}

class Centro {
    - String direccion;
    - ListaPacientes listaPacientes;
    - ListaTerapeutas listaTerapeutas;
    
    + Centro()
    
    + ListaPacientes obtenerListaPacientes()
    + ListaTerapeutas obtenerListaTerapeutas()
}

class ListaPacientes {
    - HashMap<String, Paciente> tablaHashPacientes;

    + ListaPacientes()
    
    + Paciente getPaciente(String rut)
    + boolean contienePaciente(String rut)
    + boolean agregarPaciente(Paciente paciente)
    + boolean eliminarPaciente(String rut)
    + String listarPacientes()
    + ListaSesiones getSesiones()
    + ListaSesiones getSesiones(int anio)
    + void guardarPacientesCSV()
    + void guardarSesionesCSV()
}

class ListaTerapeutas {
    - HashMap<String, Terapeuta> tablaHashTerapeutas;

    + ListaTerapeutas()

    + boolean contieneTerapeuta(String rut)
    + Terapeuta getTerapeuta(String rut)
    + String listarTerapeutas() 
}

interface MenuPrincipal {
    + JButton getGestionarPacientes()
    + JButton getSeguimientoPaciente()
    + JButton getGestionarSesiones()
    + JButton getSalirPrograma()
}

interface GestionarPaciente {
    + JButton getAgregarPaciente()
    + JButton getEliminarPaciente()
    + JButton getListarPacientes()
    + JButton getCerrarGestionarPacientes()
}

interface AgregarPaciente {
    + JTextField getNombreField()
    + JTextField getRutField()
    + JTextField getEdadField()
    + JTextField getDireccionField()
    + JTextField getHistorialField()
    + JButton getBotonAgregarPaciente()
    + JButton getCerrarAgregarPaciente()
}

interface EliminarPaciente {
    + JTextField getRutEliminarField()
    + JButton getBotonEliminarPaciente()
    + JButton getCerrarEliminarPaciente()
}

interface ListarPacientes {
    + JButton getCerrarListarPacientes()
}

interface SeguimientoPaciente {
    + JTextField getRutSeguirField()
    + JButton getBotonSeguirPaciente()
    + JButton getCerrarSeguimientoPaciente()
}

interface ListarSesiones {
    + JButton getCerrarListarSesiones()
}

interface GestionarSesion {
    + JButton getAgregarSesion()
    + JButton getEliminarSesion()
    + JButton getFiltrarSesiones()
    + JButton getCerrarGestionarSesion()
}

interface AgregarSesion {
    + JTextField getRutTerapeutaField()
    + JTextField getRutPacienteField()
    + JTextField getFechaField()
    + JTextField getTerapiaField()
    + JTextField getNotaField()
    + JTextField getComentariosField()
    + JTextField getDuracionField()
    + JButton getBotonAgregarSesion()
    + JButton getCerrarAgregarSesion()
}

interface BuscarEliminarSesion {
    + JTextField getRutBuscarSesionField()
    + JButton getBotonBuscarRut()
    + JButton getCerrarBuscarEliminarSesion()
}

interface EliminarSesion {
    + JTextField getFechaEliminarField()
    + JButton getBotonEliminarSesion()
    + JButton getCerrarEliminarSesion()
}

interface FiltrarSesiones {
    + JButton getFiltrarTodas()
    + JButton getFiltrarPorAño()
    + JButton getFiltrarPorTerapueta()
    + JButton getCerrarFiltrarSesiones()
}

interface ConsultaAño {
    + JTextField getAñoFiltroField()
    + JButton getBotonFiltrar()
    + JButton getCerrarConsultaAño()
}

interface ConsultaTerapeuta {
    + JTextField getRutTerapeutaField()
    + JButton getBotonFiltrar()
    + JButton getCerrarConsultaTerapeuta()
}

Centro -up-|> Controlador : Es llamado por
ListaPacientes -up-|> Centro : Contiene
ListaTerapeutas -up-|> Centro : Contiene

MenuPrincipal -down-|> Controlador : Es llamado por
GestionarPaciente -down-|> MenuPrincipal : Contiene
AgregarPaciente -down-|> GestionarPaciente : Es Manejado
EliminarPaciente -down-|> GestionarPaciente : Es Manejado
ListarPacientes -down-|> GestionarPaciente : Es Manejado
SeguimientoPaciente -down-|> MenuPrincipal : Contiene
SeguimientoPaciente -up-|> ListarSesiones : Llama a
GestionarSesion -down-|> MenuPrincipal : Contiene
AgregarSesion -down-|> GestionarSesion : Es Manejado
BuscarEliminarSesion -down-|> GestionarSesion :Es Manejado
EliminarSesion -down-|> BuscarEliminarSesion : Es Manejado
FiltrarSesiones -down-|> GestionarSesion : Es Manejado
ConsultaAño -down-|> FiltrarSesiones : Es Manejado
ConsultaAño -up-|> ListarSesiones : Llama a
ConsultaTerapeuta -down-|> FiltrarSesiones : Es Manejado
ConsultaTerapeuta -up-|> ListarSesiones : Llama a
@enduml
